# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b936f3a5db0a96f4614c55334c224450c0ea3f82a35b1607770f3e3c732ec6ebee1d466fca4a23406321851a816cc7213b176c30aa5b7c5872e6facfd8ce1e79

test:
  secret_key_base: 35286d6005dbc439b1531919d14071a02ccd460f5a9f69cf11073163a7bde15c6581ff49d6724abce9cfe21099a6e06179ac0525b70d25e47c21d46afc41515d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  S3_BUCKET_NAME:  <%= ENV["S3_BUCKET_NAME"] %>
  PUBLISHABLE_KEY: <%= ENV["PUBLISHABLE_KEY"] %>
